juliansteenbakker/mobile_scanner

CHANGELOG.md, lib/mobile_scanner.dart, lib/src/mobile_scanner.dart, lib/src/mobile_scanner_controller.dart
=> imp: export MobileScannerArguments

example/lib/barcode_scanner_controller.dart, example/lib/barcode_scanner_without_controller.dart, example/lib/main.dart, lib/src/mobile_scanner.dart
=> bug: fix disposing controller

lib/src/mobile_scanner.dart, lib/src/mobile_scanner_controller.dart
=> bug: add check to resume start call

CHANGELOG.md, android/src/main/kotlin/dev/steenbakker/mobile_scanner/BarcodeFormats.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt, example/lib/barcode_scanner_controller.dart, ios/Classes/SwiftMobileScannerPlugin.swift, lib/src/mobile_scanner.dart, lib/src/mobile_scanner_controller.dart, lib/src/objects/barcode.dart
=> Barcode formats allowed

ios/mobile_scanner.podspec
=> imp: constraint mlkit lib to latest version

android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
=> bug: fixed hot reload not working

README.md
Thank you for this library. I just tried to use it and flutter complained about `barcode.rawValue` can be null.
If there is a cleaner way (in dart) to make this work, please let me know and I am happy to adapt the PR.
=> Enhance documentation: barcode.rawValue can be null 

android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt, example/ios/Runner.xcodeproj/project.pbxproj, example/ios/Runner/Info.plist, example/lib/barcode_scanner_window.dart, example/lib/main.dart, ios/Classes/SwiftMobileScannerPlugin.swift, lib/src/mobile_scanner.dart, lib/src/mobile_scanner_controller.dart, lib/src/objects/barcode_utility.dart, macos/Classes/MobileScannerPlugin.swift
Implements https://github.com/juliansteenbakker/mobile_scanner/issues/11 for IOS, Android & MacOS
=> Add scanWindow to optionally limit scan area

.github/workflows/flutter.yml
@juliansteenbakker 
- Only build on pull requests and merging to master
- Update all github actions
- Cache flutter sdk
=> update github actions

.github/workflows/release-please.yml, .github/workflows/semantic-pr.yml
Hello,
Pierre from Open Food Facts (https://github.com/openfoodfacts/smooth-app)
We're currently investigating the whole scanning situation with Flutter, as well as plugins with CameraX and MLKit, and here's a proposal to generate changelogs for mobile_scanner
ci: Add Release Please to auto-generate changelogs
ci: Enforce semantic Pull Requests to make changelogs possible
- #260
=> ci: Add Release Please to auto-generate changelogs

.github/CODEOWNERS
=> ci: Add Codeowners

.github/workflows/auto-assign-pr.yml
=> ci: auto-assign PRs

lib/src/mobile_scanner.dart, lib/src/mobile_scanner_controller.dart
- Add callback to authorization status request.
- Useful to display a "warning" / "explanation" widget when user denied authorization.
- https://github.com/juliansteenbakker/mobile_scanner/issues/67
=> feat: Add permission callback

ios/Classes/SwiftMobileScannerPlugin.swift, lib/src/mobile_scanner_controller.dart
- Add support for multiple formats on iOS
=> fix: Add support for multiple formats on iOS

android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt, example/android/app/src/main/AndroidManifest.xml, example/android/app/src/main/kotlin/dev/steenbakker/mobile_scanner_example/MainActivity.kt
- Fix the error of requestCode value range
=> fix: Fix the error of requestCode value range.

README.md
=> docs: add a note in the `README.md` that you need to grant camera permission in XCode for macOS

CHANGELOG.md, lib/src/mobile_scanner_controller.dart, macos/Classes/MobileScannerPlugin.swift
=> imp: error handling

lib/src/mobile_scanner_exception.dart
Without this, I see just `instance of 'MobileScannerException'` in console
=> fix: add toString method to MobileScannerException

example/lib/barcode_scanner_controller.dart, lib/mobile_scanner_web_plugin.dart, lib/src/mobile_scanner_controller.dart, lib/src/web/base.dart, lib/src/web/zxing.dart
Closes https://github.com/juliansteenbakker/mobile_scanner/issues/344
=> feat(web): torch support

CHANGELOG.md, ios/Classes/MobileScanner.swift, ios/Classes/SwiftMobileScannerPlugin.swift
=> fix(ios): fix torch

android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerCallbacks.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerExceptions.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt, example/ios/Runner.xcodeproj/project.pbxproj, example/ios/Runner/Info.plist, example/lib/barcode_scanner_controller.dart, example/lib/barcode_scanner_pageview.dart, example/lib/main.dart, example/lib/scanner_error_widget.dart, example/macos/Podfile, example/macos/Runner.xcodeproj/project.pbxproj, lib/src/mobile_scanner.dart, lib/src/mobile_scanner_controller.dart
=> fix: parameter not resetting

lib/src/web/utils.dart
This should work with the lower Flutter version as well
We need these changes because of regression of https://github.com/flutter/flutter/issues/58428
=> fix(web): fix loading js scripts in debug mode in flutter 3.7

lib/src/mobile_scanner.dart
=> fix: Multiple-listener-registiration

ios/Classes/SwiftMobileScannerPlugin.swift
=> fix: fixed barcodes not found on analyzeImage

lib/src/mobile_scanner_controller.dart
fix: 'Uint8List' isn't a type
IAdded import for dart:typed_data.
Refs: #514
=> fix: 'Uint8List' isn't a type

lib/mobile_scanner_web_plugin.dart
=> fix(web): waiting for js libs to load

ios/Classes/MobileScanner.swift, lib/src/mobile_scanner_controller.dart, lib/src/objects/barcode_capture.dart
Details: https://github.com/juliansteenbakker/mobile_scanner/issues/532
=> fix: ios gallery typecast issue

lib/src/mobile_scanner.dart
This pull request implements the fix suggested in issue #531
=> fix: Fixes Issue #531

lib/src/mobile_scanner_controller.dart
=> fix: fixed onDetect not working with analyzeImage

CHANGELOG.md, ios/mobile_scanner.podspec, pubspec.yaml
=> imp: upgrade GoogleMLKit/BarcodeScanning to 4.0.0

.github/workflows/flutter.yml
dart format instead of the deprecated flutter format
=> Ci: dart format instead of the deprecated flutter format

example/ios/Runner.xcodeproj/project.pbxproj, ios/Classes/MobileScanner.swift, ios/Classes/SwiftMobileScannerPlugin.swift
This removes a threading warning (and potentially jank).
=> fix: Start running the capture session on a background thread

android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/utils/Yuv.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/utils/YuvToRgbConverter.kt
- fix(ScanImage): fix android image result is not correct format and orientation
=> fix(ScanImage): fix android image result is not correct format and orientation

macos/Classes/MobileScannerPlugin.swift
- Respect `detectionTimeout` on iOS devices, instead of arbitrarily waiting 10 frames
- Don't start a second scan until the first one is done, to keep memory usage more fixed if the device is slow
=> fix: Respect detectionTimeout on iOS

ios/Classes/MobileScanner.swift
=> fix: Guard against a nil device in the background queue

ios/Classes/MobileScanner.swift, ios/Classes/SwiftMobileScannerPlugin.swift
This PR is a port of https://github.com/juliansteenbakker/mobile_scanner/pull/675 but for iOS.
That PR erroneously indicated iOS, but implemented it for MacOS instead.
Fixes #787
=> fix: Port scan timeout to iOS

example/ios/Runner.xcodeproj/project.pbxproj, example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, example/ios/Runner/Info.plist, example/lib/main.dart, example/lib/mobile_scanner_overlay.dart, example/macos/Runner.xcodeproj/project.pbxproj, example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
Here are the things that I have done
1) Added an overlay text which would show Please scan QR code when no QR code is scanned
2) Added a scanwindow and added white border radius to it. 
3) Added two extra buttons namely flashlight and toggleCamera view.
4) Modified the functionality of FAB. The FAB is now invisible once the camera state opens.
Please review the PR and tell me if you need any changes to it or any new additions to it.
=> feat: Scanner with overlay screen added

example/lib/mobile_scanner_overlay.dart, lib/src/mobile_scanner.dart
This PR removes an obsolete ValueNotifier from one of the samples, and also fixes a typo.
=> fix: remove extra value notifier from sample; fix typo

lib/src/mobile_scanner.dart, lib/src/mobile_scanner_controller.dart
This PR fixes a cast that could fails, by handling PlatformException in the cast as well.
It also fixes the probable cause of the original cast failing.
Fixes #806
=> fix: Handle unhandled exception from the state call

CHANGELOG.md, ios/mobile_scanner.podspec, macos/mobile_scanner.podspec, pubspec.yaml
@juliansteenbakker I updated the changelog with the fixes that we approved over the last few days.
=> feat: Prepare changelog for version 3.5.0

android/.gitignore, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, example/android/app/build.gradle, example/android/app/src/debug/AndroidManifest.xml, example/android/app/src/main/AndroidManifest.xml, example/android/app/src/main/kotlin/dev/steenbakker/mobile_scanner_example/MainActivity.kt, example/android/app/src/main/res/values-night/styles.xml, example/android/app/src/main/res/values/styles.xml, example/android/app/src/profile/AndroidManifest.xml, example/android/gradle/wrapper/gradle-wrapper.properties, example/android/settings.gradle
This PR updates the Android setup with some updates from the `flutter create` template.
=> feat: Update Android setup

android/build.gradle, android/proguard-rules.pro
=> feat: Add proguard file to plugin

CHANGELOG.md, ios/mobile_scanner.podspec, macos/mobile_scanner.podspec, pubspec.yaml
This release contains a bugfix for main thread messaging issues, a proguard file setup for consumers of the Android plugin,
and the nullability improvements from the past few fixes.
=> feat: Release v3.5.1

CHANGELOG.md, ios/mobile_scanner.podspec, macos/mobile_scanner.podspec, pubspec.yaml
This PR bumps the package version and amends the Android permission fix to the changelog
=> feat: Release 3.5.5

ios/Classes/MobileScanner.swift
=> fix: Use default selectors instead of a discovery session

android/build.gradle
I found a duplicate line while reading the code.
Thanks for everything !
=> chore: remove duplicate Android library

CHANGELOG.md, example/lib/barcode_list_scanner_controller.dart, example/lib/barcode_scanner_controller.dart, example/lib/barcode_scanner_zoom.dart, ios/Classes/MobileScanner.swift, macos/Classes/MobileScannerPlugin.swift, pubspec.yaml
=> fix: Fix nil capture session crash on iOS / MacOS

example/lib/scanned_barcode_label.dart
Thank you for developing a useful package.
I fixed typo in `example/lib/scanned_barcode_label.dart`.
=> fix: fix typo

CHANGELOG.md, README.md, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/objects/MobileScannerStartParameters.kt, example/ios/Runner.xcodeproj/project.pbxproj, example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, example/ios/Runner/Info.plist, example/lib/barcode_scanner_controller.dart, example/lib/scanner_button_widgets.dart, example/macos/Runner.xcodeproj/project.pbxproj, example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, ios/Classes/MobileScanner.swift, ios/Classes/MobileScannerPlugin.swift, ios/Classes/MobileScannerUtilities.swift, ios/mobile_scanner.podspec, lib/mobile_scanner.dart, lib/src/enums/torch_state.dart, lib/src/method_channel/mobile_scanner_method_channel.dart, lib/src/mobile_scanner_controller.dart, lib/src/mobile_scanner_exception.dart, lib/src/mobile_scanner_platform_interface.dart, lib/src/mobile_scanner_view_attributes.dart, lib/src/web/mobile_scanner_web.dart, macos/Classes/MobileScannerPlugin.swift, macos/mobile_scanner.podspec, test/enums/torch_state_test.dart
=> fix: provide correct initial torch state

example/android/app/build.gradle, example/android/gradle/wrapper/gradle-wrapper.properties, example/android/settings.gradle
this update for handle gradle issue on new flutter version and on mac device when build on android
=> chore: update gradle and java in example app

CHANGELOG.md, pubspec.yaml
Due to some demand for the analyzeImage fixes, I am increasing the version 7.0.0 beta version from 3 to 4 and will publish a new beta version with the available fixes.
=> chore: increase version 7.0.0 beta to version 4

pubspec.yaml
This PR fixes a constraint issue that was raised by the Pub.dev publish validator
=> fix: use version range for collection

android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt, example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, ios/Classes/MobileScanner.swift, ios/Classes/MobileScannerPlugin.swift, lib/src/method_channel/mobile_scanner_method_channel.dart, lib/src/mobile_scanner.dart, macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift
Fixes hot reload function by adding force parameter to `stop()`, and calling this on every start when `kDebugMode` is true. 
Merge after #1392 
Fixes #773 
Fixes #1037 
possibly fixes #1247
=> fix: hot reload
