lib/src/mobile_scanner.dart
This PR improves when a controller should be initialized and disposed. This will give a user the option to dispose a controller when the controller is created by the user. Currently, disposing a user-created controller is handled by the package itself, but by letting a user dispose, we can prevent calling the `dispose` method being called twice.
=> fix: Handle all cases when a controller should be initialized and disposed

lib/src/objects/barcode.dart
Added null-safety to prevent the packages from throwing errors log if there is not enough sufficient data from the QR code.
**Issue:** QR code (UrlBookmark Type) is required to return title and url. Null exception thrown upon testing at generated QR code that returns empty title.
**Solution:** Add nullable String if the QR code returns empty title. Also, added nullable variable to other variables.
=> Enhancement: Add null-safety variable

android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
After user confirm the camera request, the apps will be force close because
```
Fatal Exception: java.lang.IllegalArgumentException
No supported surface combination is found for camera device - Id : 0. May be attempting to bind too many use cases. Existing surfaces: [SurfaceConfig{configType=PRIV, configSize=PREVIEW}, SurfaceConfig{configType=YUV, configSize=ANALYSIS}] New configs: [androidx.camera.core.impl.y0@b351737, androidx.camera.core.impl.q1@d784c36]
```
so unbindAll() camera provider before binding should be fix the problem
Tested on Google Pixel 3, Android 12
Flutter 2.23, Dart 2.12
=> Call cameraProvider.unbindAll() before create preview

android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
Flutter master recently added many @NonNull annotations on interface/class definitions and it breaks method overrides.
I think the PR should not be merged until the change lands on stable though I want to share the PR for future referencing purpose.
=> For #28, we need a little change on method to override.

android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
Hello !
Android application seems to crash when scanning a "ContactInfo" ( vcard ) qrcode.
See below for an example of a qrcode causing the app to crash.
`{name=barcode, data={corners=[{x=105.0, y=213.0}, {x=342.0, y=246.0}, {x=353.0, y=486.0}, {x=88.0, y=501.0}], format=256, rawBytes=[B@e33802, rawValue=BEGIN:VCARD
D/DEBUG_(32613): VERSION:3.0
D/DEBUG_(32613): N:bbbbb;aaaa
D/DEBUG_(32613): FN:aaaa bbbbb
D/DEBUG_(32613): TITLE:je sais pas
D/DEBUG_(32613): ORG:toto corp
D/DEBUG_(32613): URL:towaanu.com
D/DEBUG_(32613): EMAIL;TYPE=INTERNET:aaaaaa@towaanu.com
D/DEBUG_(32613): TEL;TYPE=voice,work,pref:00000000
D/DEBUG_(32613): TEL;TYPE=voice,home,pref:00000000
D/DEBUG_(32613): TEL;TYPE=voice,cell,pref:0000000
D/DEBUG_(32613): TEL;TYPE=fax,work,pref:00000
D/DEBUG_(32613): …
=> fix exception with adresses when scanning ContactInfo qrcode

example/android/app/src/main/AndroidManifest.xml
The correct is package name is `dev.steenbakker.mobile_scanner_example`:
https://github.com/juliansteenbakker/mobile_scanner/blob/0b415240715b1000552b2c3bd45853e3e78e3cd0/example/android/app/build.gradle#L46
=> fix: use correct package name in `AndroidManifest.xml` in example

lib/src/mobile_scanner.dart
When trying to implement the fixes suggested in #156 I stumbled upon a compiler error with the `WidgetsBinding` observers. This is a simple fix to prevent that.
=> Preventing compilation error when adding or removing a WidgetsBinding observer

android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt, ios/Classes/Util.swift, lib/src/objects/barcode.dart
Enables the use of "displayValue" included in MLKit.
This can be used to easily read non-UTF-8 strings.
- https://developers.google.com/android/reference/com/google/mlkit/vision/barcode/common/Barcode#public-string-getdisplayvalue
- https://developers.google.com/ml-kit/reference/swift/mlkitbarcodescanning/api/reference/Classes/Barcode#displayvalue
=> feat: enable displayValue

lib/src/mobile_scanner.dart, lib/src/mobile_scanner_controller.dart
Resuming the app also starts the camera, but this is inconvenient if the developer wants to explicitly control it.
This pull request fixes this.
I am using Deepl.
=> add autoResume Option

lib/src/mobile_scanner.dart, lib/src/mobile_scanner_controller.dart
- start() call removed from MobileScannerController constructor
- MobileScanner widget starts controller from initState
- _controllerHashcode made static to keep the same value on new instances
- null-safe validations added to data casting from map, like `hasTorch = startResult['torchable'] as bool? ?? false` that sometimes caused exception on web when trying to get null torchable value from map
Possible fixes:
- [ISSUE-144](https://github.com/juliansteenbakker/mobile_scanner/issues/144)
- [ISSUE-101](https://github.com/juliansteenbakker/mobile_scanner/issues/101)
Tested in: iOS 15.5, Android 8.1.0 and Chrome 101.0.4951.41
=> Improvements

lib/src/mobile_scanner.dart
Removes the unused `LayoutBuilder` to support calculating intrinsic dimensions for `MobileScanner`.
Calculating intrinsic dimensions can be useful in some cases. It is especially required when creating specify layouts using `SingleChildScrollView` as stated in the documentation (https://api.flutter.dev/flutter/widgets/SingleChildScrollView-class.html#expanding-content-to-fit-the-viewport).
=> Remove unused LayoutBuilder

android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt, example/lib/barcode_scanner_window.dart
this pull request is a temp workaround to fix android scan window by manually flipping the scan image 90 degrees (switching width and height). this is in no way a good solution as it doesn't guarantee to work on all devices. currently something is wrong with the camera rotation (try and flip example to landscape) this should probably be fixed before also fixing it here. 
[how to fix rotation](https://developer.android.com/training/camerax/configuration#rotation)
=> adds hardcoded android scanwindow fix

README.md, example/lib/barcode_scanner_returning_image.dart, example/lib/main.dart, ios/Classes/SwiftMobileScannerPlugin.swift, lib/src/mobile_scanner_controller.dart, lib/src/objects/barcode.dart
New controller option `returnImage`. When set to true a UInt8List containing the latest frame is returned with the `barcode` event.
Good things:
- Seems to work. 
Bad things:
- iOS only
- Returned image is JPEG at 0.8 compression only
- Often get a blurry frame back. Good enough to scan, not great for verification. Not sure what could be done about that, if anything.
Things that could be added:
- Configurable image compression, resizing, format
- Helper method to crop the image using the `corners` to return just the barcode.
See: #251
=> optionally return image with barcode

lib/mobile_scanner_web_plugin.dart, lib/src/mobile_scanner_controller.dart, lib/src/web/jsqr.dart
Hi!, 
currently the jsQR exposes `data` and `binaryData` properties of the object as a result of its `scan: QRCode` method.
However, the mobile_scanner only ever uses the data.
In case the QRCode payload does not return a stringified data property, it still does return `binaryData` which corresponds 1:1 to the `rawBytes` of the mobile_scanner Barcode object. Otherwise, if you scan a QR code which payload is only binary data, the mobile_scanner returns null.
PS: I'm not a jsQR expert, but it seems to me that logically binaryData will never be null, otherwise the detection itself failed?
Hence the PR, if you have any comments I'm happy to review them.
=> expose the binaryData from the jsQR library

lib/mobile_scanner_web_plugin.dart
- This blocks error reporting via runZonedGuarded
- Also this is should be called before calling runApp method via main method
=> fix: removed WidgetsFlutterBinding.ensureInitialized() for WEB plugin

lib/src/mobile_scanner.dart
If the QR code contains binary data that is not UTF8 (aka malformed code points) then the `rawValue` will be null. And then the if statement to check if `lastScanned` equals the `rawValue` will never return true as the value never gets set.
So instead of comparing the string representations I changed the code to compare the `Uint8List`, that way the first scan of a malformed QR code will succeed.
=> fix: should check for the raw bytes instead of string, in case of a malformed utf8 string

CHANGELOG.md, android/src/main/kotlin/dev/steenbakker/mobile_scanner/BarcodeHandler.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MethodCallHandlerImpl.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerPermissions.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerPlugin.kt, example/lib/barcode_list_scanner_controller.dart, example/lib/barcode_scanner_controller.dart, example/lib/barcode_scanner_returning_image.dart, example/lib/barcode_scanner_without_controller.dart, example/lib/scanner_error_widget.dart, lib/src/mobile_scanner.dart, lib/src/mobile_scanner_controller.dart, pubspec.yaml
This PR fixes #402
It also cleans up the plugin internals a bit:
- The `MobileScannerPlugin.kt` file now only handles Activity lifecycle things.
- The permission handling code was moved to its own class
- The method call handler was moved to its own class
- The barcode handler now only requires the BinaryMessenger instead of the entire binding
- Updates the example app to properly display permission errors in the UI
- Adds a new `errorBuilder` argument to the mobile scanner widget
=> fix: Android permission bug

macos/Classes/MobileScannerPlugin.swift
This PR checks textureId in beginning of captureOutput to avoid Unexpected exception in macOS.
In my demo app, it seems to work as expected.
=> fix: Ignore invalid textureId in captureOutput

ios/Classes/MobileScanner.swift
closes #468
I didn't notice a scanning speed enhancement, but users can now focus and scan from closer distances on iPhone 12, 13, and 14. Specific to iPhone14, I was actually able to find barcodes of a particular size and distortion that required this feature in order to be scanned at all.
=> feat(iOS): Support the most recent camera device types

CHANGELOG.md, ios/Classes/MobileScanner.swift
- Disable face-driven autofocus on iOS 15.4+
- Enable continuous autofocus if available
=> feat(iOS): Tweak iOS camera focus settings

ios/Classes/MobileScanner.swift
Evidently I was testing against a cached old commit when I was testing this change, and the change in [#500](https://github.com/juliansteenbakker/mobile_scanner/pull/500) has code that doesn't compile.
=> fix: Fix bad `AVCaptureDevice.isFocusModeSupported` call

lib/src/mobile_scanner_controller.dart
This PR avoids the error in #426 in the case `returnImage` is specified as null. Also, it actually fixes the intended behavior of the `returnImage` argument.
=> fix: Do not return image if returnImage is false / not specified.

ios/Classes/SwiftMobileScannerPlugin.swift
Impacted file:
* `SwiftMobileScannerPlugin.swift`: explicit returned type for `compactMap`, needed for not top versions of Xcode
=> fix: 544 - explicit returned type for compactMap

android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerCallbacks.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt, ios/Classes/MobileScanner.swift, ios/Classes/SwiftMobileScannerPlugin.swift, lib/src/mobile_scanner_controller.dart
This PR is for improvements zoom scale feature, especially for avoiding to select ultra wide camera unintentionally. Please review and merge if looks good.
* added `zoomScale` value notifier in MobileScannerController for the application to know the zoom scale value set actually.  
The value is notified from the native SDK(CameraX/AVFoundation).
* added `resetZoomScale()` in MobileScannerController to reset zoom ratio with 1x.  
Both Android and iOS, if the device have ultra-wide camera, calling `setZoomScale` with small value causes to use ultra-wide camera and may be diffcult to detect barcodes.
`resetZoomScale()` is useful to use standard camera with zoom 1x.
`setZoomScale()` with the specific value can realize same effect, but added `resetZoomScale` for avoiding floating point errors. …
=> feat: Improvements about zoom scale value and ultra-wide camera

CHANGELOG.md, android/build.gradle, pubspec.yaml
This PR adds the `namespace` attribute to `mobile_scanner`'s build.gradle. The `package` attribute is left in the Manifest for now, as it is required for older projects that do not recognise the new namespace attribute.
The example app already had its namespace attribute set, so that is left as-is.
Fixes #602
=> fix: Add namespace to mobile_scanner for Android

.github/workflows/flutter.yml, analysis_options.yaml, lib/mobile_scanner.dart, lib/mobile_scanner_web.dart, lib/src/mobile_scanner_controller.dart, lib/src/web/utils.dart, test/mobile_scanner_test.dart
This fixes the format command in CI, as the `-n` option is not supported by `dart format`.
It also fixes the analysis failures in CI.
See also https://github.com/juliansteenbakker/mobile_scanner/pull/651#discussion_r1210305593
cc @teolemon
=> fix: Remove -n option from format command

lib/src/mobile_scanner.dart
This PR fixes an issue where `IntrinsicHeight` could not be used for the placeholder / error builder.
It also cleans up minor usages of the `Size` class.
- Addresses https://github.com/juliansteenbakker/mobile_scanner/pull/373#discussion_r1148913892
cc @saibotma Is this what you were referring to?
=> fix: Use MediaQuery.sizeOf(context) instead of topmost LayoutBuilder

android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
Hello,
In some rare cases, the callback of the `SurfaceProvider` may be call after the camera is stopped.
In that case, `textureEntry` is null, generating a `NullPointerException` (#666)
This PR ensure that the camera is not stopped in the callback.
=> feat: In the `SurfacePreview`, ensure the camera is not stopped

macos/Classes/MobileScannerPlugin.swift
Fix some macOS build errors:
- Date.now (https://developer.apple.com/documentation/foundation/date/3766590-now) is only available in macOS 12.0 and above while Date.init() (https://developer.apple.com/documentation/foundation/date/1780470-init) is available in macOS 10.10 and above
- Int must be explicitly converted to Double
- self must be specified explicitly to access imagesCurrentlyBeingProcessed in closure
=> fix: macos build error

lib/src/mobile_scanner.dart
- Added back the LayoutBuilder widget to get the correct values for the widgetSize instead of the screen size.
- Pull request for https://github.com/juliansteenbakker/mobile_scanner/issues/745
- This pull request might not be needed since there is another pull request that would resolve the issue https://github.com/juliansteenbakker/mobile_scanner/pull/721
=> fix: Add back LayoutBuilder to calculate the correct widgetSize

README.md, android/build.gradle
Hey 👋 
This is the PR based on https://github.com/juliansteenbakker/mobile_scanner/issues/635#issuecomment-1754828349
This should also close this issue: https://github.com/juliansteenbakker/mobile_scanner/issues/235
I added the possible configuration to the readme and made the part about bundled vs unbundled a bit more concise.
Let me know if you need anything else.
Cheers
=> feat: Add optional gradle property for unbundled scanner

android/build.gradle
This change fixes the issue #729 
As I shared in the mentioned issue to use Kotlin 1.9.x project needs to be already on Android Gradle Plugin 8.x, which is not something that every project can already do now. Thus, I suggest to rollback Kotlin version for better compatibility like I had to do in Plus Plugins as well (see https://github.com/fluttercommunity/plus_plugins/issues/2251)
=> fix: Change Kotlin version from 1.9.10 to 1.7.22 to fix Android builds

lib/src/mobile_scanner.dart, lib/src/scan_window_calculation.dart, test/scan_window_test.dart
This is a cherry-pick of @MBulli his changes in #721 with the following additions:
- documentation adjustments for the scan window function
- using named parameters for the two `Size` arguments
- formatting adjustments by adding missing comma's in the test
Test still passes locally.
Fixes #633
=> fix: scan window fix (cherry-pick)

android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
Fix https://github.com/juliansteenbakker/mobile_scanner/issues/799 introduced by https://github.com/juliansteenbakker/mobile_scanner/pull/785
When using cameraResolution, actual manner of getting display object lead to app crash.
Tested on Android >= 30 and <= 30.
=> fix: Null exception when getting activity display on Android API >= 30

ios/Classes/MobileScannerUtilities.swift
This PR fix the weird orientation seen in https://github.com/juliansteenbakker/mobile_scanner/issues/801.
I didn't find a way to determine the original orientation from the buffer, but it's definitly weird to fallback to the `left`.
=> fix: iOS Orientation change from .left to .up

example/ios/Podfile, example/ios/Runner.xcodeproj/project.pbxproj, example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, example/ios/Runner/Info.plist, example/ios/RunnerTests/RunnerTests.swift, example/macos/Podfile, example/macos/Runner.xcodeproj/project.pbxproj, example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, example/macos/Runner/Configs/AppInfo.xcconfig, example/macos/Runner/MainFlutterWindow.swift, example/macos/RunnerTests/RunnerTests.swift
This PR adds a RunnerTests setup to the iOS/MacOS example app.
It adds the RunnerTests stub that is added by the template. (with the original function commented out, since it will be replaced in the end)
With the large changes to the iOS/MacOS workspace files, I've tested iOS/MacOS and they still run correctly.
The new RunnerTests also show up in the project navigator for iOS/MacOS, so that works as well.
=> feat: RunnerTests for iOS/MacOS

android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/objects/BarcodeFormats.kt, lib/mobile_scanner_web_plugin.dart, lib/src/mobile_scanner_controller.dart
This PR adjusts the Android implementation to accept the raw value of the format, to bring it in line with other platforms.
It also removes an unused argument, formats a Kotlin file, and moves the `cameraResolution` argument out of a platform check. If the `cameraResolution` is not supported by a platform, it is ignored in the implementation anyway.
Lastly, all the enums now use their `rawValue` instead of their `index` as serialized value to the platform side.
=> fix: use rawValue on Android as well for formats

CHANGELOG.md, example/lib/barcode_scanner_window.dart, lib/mobile_scanner.dart, lib/mobile_scanner_web_plugin.dart, lib/src/barcode_utility.dart, lib/src/mobile_scanner_controller.dart, lib/src/objects/address.dart, lib/src/objects/barcode.dart, lib/src/objects/barcode_capture.dart, lib/src/objects/calendar_event.dart, lib/src/objects/contact_info.dart, lib/src/objects/driver_license.dart, lib/src/objects/email.dart, lib/src/objects/geo_point.dart, lib/src/objects/person_name.dart, lib/src/objects/phone.dart, lib/src/objects/sms.dart, lib/src/objects/url_bookmark.dart, lib/src/objects/wifi.dart
The classes in `src/objects/barcode.dart` have been moved to their own files.
The API for these classes stays the same unless otherwise noted below.
- The `type` attribute of the `Address`, `Email`, `Phone` is now non-null.
- The enums now specify `unknown` as their value, instead of null.
- The `phoneNumber` of an SMS is now non-null.
- This was an assumption that I made. The empty string is used in place of null.
- The `latitude` and `longitude` of a `GeoPoint` are now non-null.
- This was an assumption that I made. A valid point should have both latitude and longitude anyway
- If either is null, the `GeoPoint.fromNative` method returns `0,0` as fallback.
- The `url` of a `UrlBookmark` is now non-null.
- This was an assumption that I made. The empty string is used in place of null.
- …
=> feat: Move classes into their own files

CHANGELOG.md, lib/src/objects/barcode.dart
This PR adds some fixes for the Barcode class that were not included in #818 
- The default arguments for `type` and `format` are now correctly `BarcodeType.unknown` and `BarcodeFormat.unknown`,
rather than `BarcodeType.text` and `BarcodeFormat.ean13`
- The `fromNative` constructor is now a factory constructor and has been moved to the top of the file, under the regular constructor
- The class attributes have been sorted alphabetically
- The documentation for the class attributes has been updated
=> feat: Barcode class fixes

CHANGELOG.md
The analyzer accepts `Map` and `Map<Object?, Object?>` without restrictions. Thus this is actually not a breaking change.
Example program:
```
void main() {
final Map m = {};
final Map<Object?, Object?> m2 = <Object?, Object?>{};
final Map<Object?, Object?> m3 = {};
foo(m); // LinkedHashMap<dynamic, dynamic>
foo(m2); // LinkedHashMap<Object?, Object?>
foo(m3); // LinkedHashMap<Object?, Object?>
}
void foo(Map<Object?, Object?> input) {
print(input.runtimeType);
}
```
=> fix: Remove redundant breaking change notice for Map<Object?, Object?> change

CHANGELOG.md, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt, ios/Classes/BarcodeHandler.swift, ios/Classes/MobileScanner.swift, ios/Classes/MobileScannerPlugin.swift, ios/Classes/MobileScannerUtilities.swift, macos/Classes/MobileScannerPlugin.swift
This PR fixes the missing switches to the main thread on Android, iOS and MacOS.
Changes in this PR:
- Added the two missing main looper switches for Android
- Removed the unused `event` property from the iOS `BarcodeHandler`
- Added a missing `DispatchQueue.main.async` switch to the iOS `BarcodeHandler`
- Moved the `DispatchQueue.main.async` from inside the iOS `MobileScanner.start()` method to the argument that is passed to the completion block. This makes it easier to read.
- Fixed some `result(nil)` calls that were called _after_ catch blocks on iOS. This would result in the result getting called twice.
- Added missing `DispatchQueue.main.async` switches to the iOS `analyzeImage` implementation
- Removed the unused `Error.throwNative` extension from the iOS implementation.
- I chose …
=> fix: Fix platform messages threading

lib/src/objects/barcode.dart
Apparently when moving the classes in #818 I missed a usage of a cast to a Map that broke.
(the `Map<String, double>` is the culprit)
This PR fixes that bug. As this bug was not yet in a released version, this PR has no version bump.
=> fix: fix a cast from a bad conversion

CHANGELOG.md, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt, macos/Classes/MobileScannerPlugin.swift
This PR fixes a bug where Android & MacOS were discarding the incoming MethodCall.Result for the `updateScanWindow()` function.
I checked the implementations for other such cases, and all other methods take the result as parameter. So `updateScanWindow()` was the only one that did not.
Fixes #730
=> fix: fix updateScanWindow() not completing on Android and MacOS

android/src/main/AndroidManifest.xml, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerExceptions.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt, ios/Classes/MobileScanner.swift, ios/Classes/MobileScannerPlugin.swift
This PR fixes some camera issues on Android by updating how we work with the camera:
- Only do safe access of the camera/cameraProvider using `?.`, instead of `!!.` which forced it.
- Added the feature flag to the manifest to denote that the camera is optional (since we now handle "no camera" properly)
- Updated the error handling for the camera provider to emit errors through a callback
- This was not working, because the errors are thrown in the camera's executor.
- Removed the unused `TorchError` class
- Updated the toggle torch code to only do this when the device has a flash unit
- Fixes two typos that checked for the wrong error type
Fixes #762 
Fixes #719
=> fix: Handle no cameras on Android

android/build.gradle
This PR bumps an Android MLKIt dependency from 18.1.0 to 18.3.0
=> chore: Bump MLKit for Android from 18.1.0 to 18.3.0

android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt, ios/Classes/MobileScanner.swift
This PR proposes a fix for the issue reported here #750, which I also encountered.
To summarize, we reset the variable that holds the list of recently scanned codes every time the mobile scanner controller is restarted. I also sorted the list to avoid false comparisons of lists with the same codes but in a different order.
Additionally, on iOS, I had a code that was being spammed even though the "noDuplicates" speed was enabled. Upon reviewing the code, I noticed that this occurred when an empty code list was returned by the scanner, which happens as soon as there are no more codes in the camera's field of view. So I added a check to ignore empty lists. In fact, this check was already present in the Android code.
=> fix: with the "noDuplicates", the same code is no longer detected after stopping and restarting the scanner

android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
When using a MobileScannerController with returnImage set to true, my android app would throw several messages about trying to call getWidth or getHeight on a recycled bitmap, this change fixes the issue and allows the app to continue and capture the image
=> fix: error with returning image on android

ios/Classes/MobileScannerPlugin.swift
A Double conversion is broken leading to an Int round result. 
(You can quickly check that here : https://online.swiftplayground.run/)
```swift
// Default conversion will use int
print(500 / 1000) // 0 
// Wrong conversion to Double
print(Double(500 / 1000)) // 0.0 
// Good conversion to Double
print(500 / Double(1000)) // 0.5
```
Important bug :).
=> fix: iOS Timeout is broken because of Double miss conversion

CHANGELOG.md, ios/mobile_scanner.podspec, macos/mobile_scanner.podspec, pubspec.yaml
This PR bumps the version to 3.5.3, to include the iOS scan timeout conversion fix.
=> feat: Bump version to 3.5.3

ios/Classes/MobileScanner.swift, macos/Classes/MobileScannerPlugin.swift
This PR fixes a crash on iOS, due to missing switches to the main dispatch queue when setting up the zoom scale & torch on the background queue.
It also adds a check for determining if the torch mode is actually supported.
For consistency, the fixes have been ported to MacOS as well.
Lastly, this PR adds stub implementations for MacOS for the scale methods, so that these do not throw unimplemented errors. I didn't find any compatible API for actually implementing that.
Fixes #884
=> fix: Fix ios torch crash

lib/src/web/zxing.dart
=> fix: return type 'int' doesn't allow null for zxingBarcodeFormat method

android/proguard-rules.pro
Some enums in android camerax API are missing after minification. Adding a general rule to keep enum fields and APIs around. Fixes #614 in my testing.
=> fix: missing methods on enums

lib/src/mobile_scanner_controller.dart
Hi, I found 2 small improvements.
- `package:flutter/cupertino.dart` seems unnecessary.
- We can avoid using `package:mobile_scanner/mobile_scanner.dart` in library-private files.
Thank you.
=> chore: Modify import statements

CHANGELOG.md
Added a note to mark which versions would require Android projects to have compileSDK 34.
The reason for this change is because since `3.5.0` the plugin uses dependencies that require compileSDK to be set to 34 as I have already explained in https://github.com/juliansteenbakker/mobile_scanner/issues/922#issuecomment-1912090475
With this change, hopefully, there will be less confused people as versions before 4.0.0 don't mention such requirement, so, potentially, there might be more issues like #922
=> docs: Add note about compileSDK requirements

CHANGELOG.md, example/pubspec.yaml, pubspec.yaml
This PR lowers the barrier to entry for the new beta to Flutter 3.16.0
The main use of the previous constraint was to use `extension types`, but that can be done as an incremental release instead. Users that are already on Flutter 3.16.0 _do_ have access to (an earlier version of) package:web and dart:js_interop which does not yet utilise extension types.
=> fix: lower the Flutter constraint to allow earlier adoption of the beta

README.md, example/README.md
Currently, it is a time-consuming task to figure out the best options to implement mobile_scanner in a custom app because because there is not general documentation for the examples found in the examples folder.
This PR adds an overview with a short description for all examples.
=> docs: add description for all examples to examples README

ios/mobile_scanner.podspec
The 5.0.0 version has the iOS privacy manifests updated for the MLKit libs themselves, but they still pulled in old versions of transitive dependencies like GoogleToolboxForMac that didn't have the necessary manifests. The 6.0.0 version updated the transitive dependencies and now the privacy manifests should be all good.
=> chore(deps): Bump GoogleMLKit/BarcodeScanning to 6.0.0

CHANGELOG.md, example/lib/barcode_scanner_window.dart, lib/src/method_channel/mobile_scanner_method_channel.dart, pubspec.yaml
current code in `lib/src/method_channel/mobile_scanner_method_channel.dart` cannot change the platform in the test code when need to change the platform. according to this thread, maybe we should change the platform os detect pattern into `defaultTargetPlatform `. 
ref:https://stackoverflow.com/questions/55233853/flutter-widget-tests-with-platform-branching
=> feat: change platform os detect pattern

CHANGELOG.md, lib/src/mobile_scanner_controller.dart, pubspec.yaml
If mobile_scanner widget is disposed while start the following exception appear : 
```
flutter: Once you have called dispose() on a MobileScannerController, it can no longer be used.
flutter: #0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:179:9)
flutter: #1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:186:6)
flutter: #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:412:27)
flutter: #3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:555:5)
flutter: #4      MobileScannerController.start (package:mobile_scanner/src/mobile_scanner_controller.dart:277:7)
```
=> fix: widget-disposed-during-start

CHANGELOG.md, example/lib/barcode_scanner_controller.dart, example/lib/barcode_scanner_listview.dart, example/lib/barcode_scanner_pageview.dart, example/lib/barcode_scanner_returning_image.dart, example/lib/barcode_scanner_window.dart, example/lib/barcode_scanner_zoom.dart, example/lib/mobile_scanner_overlay.dart, ios/mobile_scanner.podspec, macos/mobile_scanner.podspec, pubspec.yaml
When reintroducing the `autoStart` parameter, the samples were not accounted for. This PR adjusts the samples to automatically start, except for the lifecycle sample, which still manually starts. 
Fixes #1058
=> fix: Adjust autoStart values for samples

lib/src/mobile_scanner_controller.dart, lib/src/objects/start_options.dart
useNewCameraSelector is not being sent to the android backend. This forwards it with the other start options.
=> fix: connecting the useNewCameraSelector option

example/README.md
The folders name is example and not examples
=> docs: Fix typo

CHANGELOG.md, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt
This PR adds the following changes:
- Fixes a possible leak on Android relating to keeping an orphaned barcode scanner around (the one that is created when the scanner variable is declared, but not yet used)
- Fixed another possible leak where not all camera observers were released
- Reflows some part of the Android code to use early returns
- Updates `analyzeImage()` to take configurable barcode scanner options & use a short lived scanner
- Adds a way to mock the barcode scanner for testing (will be used for the NaN error fix)
For future readers, iOS does not have an equivalent release method for the scanner in the MLKit library.
It's possible that uses an autorelease pool or destructor.
Fixes https://github.com/juliansteenbakker/mobile_scanner/issues/988
Part of …
=> fix: fix barcode scanner leak on Android

CHANGELOG.md, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt, android/src/test/kotlin/dev/steenbakker/mobile_scanner/MobileScannerTest.kt
This PR fixes a crash when the scan window encounters NaN. Also adds a regression test.
Fixes #1134
=> fix: do not crash when getting NaN on Android

.github/workflows/flutter.yml, CHANGELOG.md, example/web/index.html, pubspec.yaml
=> chore: Migrate to web 1.0.0

CHANGELOG.md, ios/mobile_scanner.podspec, macos/mobile_scanner.podspec, pubspec.yaml
This PR bumps the version of `mobile_scanner` to 5.2.0
I used this version number, to not break users that have not migrated to Flutter 3.22.0
This version includes the bump for package:web and some bugfixes.
For the next version, I plan to fix the NV21 format bug and finish the Impeller migration on Android.
=> chore: Bump version to 5.2.0

CHANGELOG.md, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerUtilities.kt, example/ios/Runner/AppDelegate.swift, example/macos/Runner/AppDelegate.swift, ios/Classes/MobileScanner.swift, ios/Classes/MobileScannerPlugin.swift, ios/Classes/MobileScannerUtilities.swift, ios/mobile_scanner.podspec, lib/src/method_channel/mobile_scanner_method_channel.dart, lib/src/mobile_scanner_controller.dart, lib/src/objects/barcode.dart, lib/src/objects/barcode_capture.dart, macos/mobile_scanner.podspec, macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift, pubspec.yaml
This PR fixes a discrepancy between what is meant with the bounding box of a scanned barcode and the size of the barcode capture output image.
It also adds the following changes:
- Added support for `returnImage` on MacOS
- Fixes a bug where `returnImage` set to false would not do anything on iOS
- Cleans up some unused code and refactors some control flow to use early returns
Fixes #1162 
cc @fulstadev
=> fix: Fix discrepancy between barcode bounding box and barcode capture size

CHANGELOG.md, ios/mobile_scanner.podspec, lib/src/enums/address_type.dart, lib/src/enums/barcode_type.dart, lib/src/enums/email_type.dart, lib/src/enums/encryption_type.dart, lib/src/enums/phone_type.dart, lib/src/objects/wifi.dart, lib/src/web/mobile_scanner_web.dart, macos/mobile_scanner.podspec, pubspec.yaml, test/enums/address_type_test.dart, test/enums/barcode_type_test.dart, test/enums/email_type_test.dart, test/enums/encryption_type_test.dart, test/enums/phone_type_test.dart
=> fix: Handle unknown barcode data enum types & disable media controls

CHANGELOG.md, README.md, android/build.gradle, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt, example/lib/barcode_scanner_analyze_image.dart, example/lib/barcode_scanner_window.dart, example/lib/main.dart, example/lib/mobile_scanner_overlay.dart, ios/Classes/MobileScanner.swift, ios/Classes/MobileScannerPlugin.swift, lib/src/method_channel/mobile_scanner_method_channel.dart, lib/src/mobile_scanner_controller.dart, lib/src/mobile_scanner_platform_interface.dart, lib/src/objects/barcode.dart, lib/src/web/mobile_scanner_web.dart, lib/src/web/zxing/result.dart, lib/src/web/zxing/zxing_barcode_reader.dart, macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift
This PR adds support for specifying the formats for analyze image.
It also adds the (normalized) barcode size for the barcodes on the web and adds support for analyze image on MacOS.
Fixes #1069
=> fix: support formats for analyze image

analysis_options.yaml, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/objects/MobileScannerErrorCodes.kt, example/lib/barcode_scanner_controller.dart, ios/Classes/MobileScannerError.swift, ios/Classes/MobileScannerErrorCodes.swift, ios/Classes/MobileScannerPlugin.swift, lib/src/enums/mobile_scanner_error_code.dart, lib/src/method_channel/mobile_scanner_method_channel.dart, lib/src/mobile_scanner.dart, lib/src/mobile_scanner_exception.dart, lib/src/objects/mobile_scanner_state.dart, macos/mobile_scanner/Sources/mobile_scanner/MobileScannerErrorCodes.swift, macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift
Part of #1086 but split off to make the other diff smaller
=> fix: Clean up error codes

example/lib/scanner_button_widgets.dart
I noticed when experimenting with the overlay example, that the camera switching button had no color defined (and was invisible when I tried it in my app initially), and that the flash-unavailable icon did not take as much space as the flash icon button (and was a different size).  This attempts to fix those issues.
Before:
https://github.com/user-attachments/assets/090825e0-337a-4029-80b2-d3a0d14bd5f1
After:
https://github.com/user-attachments/assets/414fdff9-95e9-4968-a354-d7294533e689
=> fix: clean up example button widgets

example/lib/scanner_button_widgets.dart
Fixes a bug introduced in https://github.com/juliansteenbakker/mobile_scanner/pull/1186, which caused the icon to center vertically unconstrained.
I also removed the `Center` widget, because it does not appear to have any effect inside a `SizedBox`.  But I'm happy to re-add if it's necessary.
=> fix: Constrain torch unavailable example icon

CHANGELOG.md, macos/mobile_scanner.podspec, macos/mobile_scanner/Package.swift, macos/mobile_scanner/Sources/mobile_scanner/Resources/PrivacyInfo.xcprivacy
This PR adds the privacy manifest for MacOS. Built the example app to verify that the privacy manifest is included in the archive.
Fixes #1178
=> feat: add macos privacy manifest

CHANGELOG.md, README.md, android/src/main/kotlin/dev/steenbakker/mobile_scanner/BarcodeHandler.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerPermissions.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerPermissionsListener.kt, example/.gitignore, example/ios/Runner.xcodeproj/project.pbxproj, example/lib/barcode_scanner_analyze_image.dart, example/macos/Runner/AppDelegate.swift, example/macos/Runner/DebugProfile.entitlements, example/web/index.html, ios/Classes/BarcodeHandler.swift, ios/Classes/MobileScannerErrorCodes.swift, ios/Classes/MobileScannerPlugin.swift, lib/mobile_scanner.dart, lib/src/method_channel/mobile_scanner_method_channel.dart, lib/src/mobile_scanner.dart, lib/src/mobile_scanner_controller.dart, lib/src/mobile_scanner_exception.dart, lib/src/web/mobile_scanner_web.dart, lib/src/web/zxing/zxing_barcode_reader.dart, lib/src/web/zxing/zxing_exception.dart, macos/mobile_scanner/Sources/mobile_scanner/MobileScannerErrorCodes.swift, macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift
Fixes: https://github.com/juliansteenbakker/mobile_scanner/issues/1078
Fixes: https://github.com/juliansteenbakker/mobile_scanner/issues/502
=> fix: Ignore additional calls to start() when the controller is starting

CHANGELOG.md, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt, ios/Classes/MobileScannerPlugin.swift, lib/src/mobile_scanner_controller.dart, lib/src/objects/barcode_capture.dart, lib/src/web/mobile_scanner_web.dart, lib/src/web/zxing/zxing_barcode_reader.dart, macos/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift
This PR updates the behavior of `returnImage` to only refer to the bytes of the output image, not the size.
The size can always be returned, to allow users to do calculations with it (for example, together with the `Barcode.size`)
Part of https://github.com/juliansteenbakker/mobile_scanner/issues/1183
=> feat: Always return capture size

CHANGELOG.md, example/ios/Podfile, ios/mobile_scanner.podspec, lib/src/mobile_scanner.dart, macos/mobile_scanner.podspec, pubspec.yaml
Fixes #1209 
Fixes https://github.com/juliansteenbakker/mobile_scanner/issues/1210
=> fix: handle errors in onDetect; exclude armv7 for iOS

CHANGELOG.md, README.md, ios/mobile_scanner.podspec, lib/src/mobile_scanner_controller.dart, macos/mobile_scanner.podspec, pubspec.yaml
=> fix: exclude arm64 simulators

example/lib/barcode_scanner_window.dart, example/lib/mobile_scanner_overlay.dart
Fixes https://github.com/juliansteenbakker/mobile_scanner/issues/1185
I also updated the other usage of Rect.largest in `BarcodeScannerWithScanWindow`, even though it wasn't visually broken previously.  I figured it was better to keep them consistent, though.
|Before | After|
|------|-------|
| <img width="245" alt="image" src="https://github.com/user-attachments/assets/87ae7886-96c3-45b6-8cb5-44e5a9fc9268">  |   <img width="240" alt="image" src="https://github.com/user-attachments/assets/af0d61bf-6857-4d6f-867a-e2429c9e9d1b">   |
|  <img width="231" alt="image" src="https://github.com/user-attachments/assets/eeb1a65e-bcab-4201-8d89-031f99a1a48d">  | <img width="247" alt="image" src="https://github.com/user-attachments/assets/0eb6b1fd-c849-43e9-89bf-69b4b74763a7"> |
=> fix: scanner overlay example

CHANGELOG.md, example/lib/barcode_scanner_controller.dart, example/lib/barcode_scanner_pageview.dart, example/lib/barcode_scanner_returning_image.dart, example/lib/barcode_scanner_simple.dart, example/lib/barcode_scanner_window.dart, example/lib/barcode_scanner_zoom.dart, example/lib/mobile_scanner_overlay.dart, example/lib/scanner_error_widget.dart, lib/src/mobile_scanner.dart
=> fix: remove unused child argument

.github/workflows/flutter.yml, .gitignore, CHANGELOG.md, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/objects/MobileScannerErrorCodes.kt, darwin/mobile_scanner/Sources/mobile_scanner/MobileScannerErrorCodes.swift, darwin/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift, example/ios/Runner.xcodeproj/project.pbxproj, example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, example/pubspec.yaml
This PR adds the following changes:
- adjusts the iOS / MacOS implementation to throw an error when the provided file path is not an image.
- adjusts the Android implementation to throw an error when the provided file path is not an image. As reported in the issue, it was hanging previously (due to an unhandled IOException)
- enables Swift Package Manager support in the example app
Fixes https://github.com/juliansteenbakker/mobile_scanner/issues/1244
=> fix: emit an error when CIImage cannot be created

CHANGELOG.md, darwin/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift, example/macos/Runner.xcodeproj/project.pbxproj, example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
=> fix: do not hang on analyze image if there are no results

CHANGELOG.md, android/src/main/kotlin/dev/steenbakker/mobile_scanner/objects/MobileScannerErrorCodes.kt, darwin/mobile_scanner/Sources/mobile_scanner/MobileScannerErrorCodes.swift, darwin/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift, lib/src/enums/mobile_scanner_error_code.dart, lib/src/method_channel/mobile_scanner_method_channel.dart, lib/src/mobile_scanner_controller.dart
It seems that the iOS Simulator does not support the neural engine features that are required to run the Vision API,
hence why it fails to create the underlying detection model.
Fixes https://github.com/juliansteenbakker/mobile_scanner/issues/1269
=> fix: report analyze image as unsupported on iOS Simulator

darwin/mobile_scanner/Sources/mobile_scanner/MobileScannerErrorCodes.swift
This PR fixes a dangling semicolon, that is not needed in Swift.
I missed this one in #1275
=> chore: fix typo

android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
This PR is a follow up to https://github.com/navaronbracke/mobile_scanner/commit/dead58edf18a6c4e8417fcc46885f690a00b6335
The second release is redundant since we already do it a few lines above.
=> fix: remove redundant release

CHANGELOG.md, android/build.gradle, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
When returnImage is set to true,  android device experiences UI Jank when QR code is detected.
https://github.com/user-attachments/assets/a7f63de7-17e0-4b41-b557-66d283256231
- Used Coroutine for image processing task.
=> fix: fix android jank ui when returnImage is true

CHANGELOG.md, android/src/main/kotlin/dev/steenbakker/mobile_scanner/BarcodeHandler.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/DeviceOrientationListener.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/objects/MobileScannerStartParameters.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/utils/DeviceOrientationExtension.kt, example/lib/barcode_scanner_controller.dart, example/pubspec.yaml, lib/src/method_channel/android_surface_producer_delegate.dart, lib/src/method_channel/mobile_scanner_method_channel.dart, lib/src/utils/parse_device_orientation_extension.dart, pubspec.yaml, test/parse_device_orientation_test.dart
This PR adds support for Impeller on Android.
Supercedes #1277 (retargets those changes onto the new develop branch)
TODO:
Part of #867
=> feat: Android Impeller support

.github/workflows/flutter.yml, example/lib/barcode_scanner_controller.dart, example/lib/barcode_scanner_listview.dart, example/lib/barcode_scanner_pageview.dart, example/lib/barcode_scanner_returning_image.dart, example/lib/barcode_scanner_simple.dart, example/lib/barcode_scanner_window.dart, example/lib/barcode_scanner_zoom.dart, example/lib/mobile_scanner_overlay.dart, example/lib/scanner_error_widget.dart
This PR fixes the current lint warnings/errors on tip-of-tree for `master`:
- `withOpacity` is deprecated, replaced by `fromRGBO`, except for one usage of `Colors.red`, which is replaced by a hexadecimal version of said color, with the opacity applied
- an unreachable `break` statement was reported by the new version of the Dart analyzer (the respective lint now detects this case).
- `onPopWithResult` is not available for the current min sdk version, so that was adjusted from Flutter 3.22 to 3.24
=> chore: fix analysis on master

CHANGELOG.md, darwin/mobile_scanner/Sources/mobile_scanner/MobileScannerErrorCodes.swift, darwin/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift, example/ios/Runner.xcodeproj/project.pbxproj
Per the docs of `addInput` : 
```
It’s only valid to call this method if canAddInput returns true.
```
https://developer.apple.com/documentation/avfoundation/avcapturesession/addinput(_:)
Fixes https://github.com/juliansteenbakker/mobile_scanner/issues/1297
=> fix: check canAddInput for AVCaptureSession

CHANGELOG.md, lib/src/web/zxing/zxing_barcode_reader.dart
This PR bumps our default ZXing version to the latest available version.
I didn't go through the entire changelog (there might be other things we can add with this new version), but the fix for color inverted barcodes is in this dependency roll.
fixes https://github.com/juliansteenbakker/mobile_scanner/issues/1278
=> fix: bump zxing js from 0.19.1 to 0.21.3

CHANGELOG.md, darwin/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift
This PR restores support for `Barcode.rawBytes` in the Vision implementation.
This appears to be the only field that wasn't ported over, excluding the various decoded datatypes (which are MLKIt specific and might be added later)
Fixes #1315
=> fix: add payload data as raw bytes in the new iOS/MacOS implementation 

.github/workflows/flutter.yml, CHANGELOG.md, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt
This PR turns off the CameraX logging for the `Log.DEBUG`, `Log.INFO` and `Log.WARN` logging.
Per the docs of CameraX:
```
For apps that want to reduce the logs produced by CameraX, set it to Log. ERROR to avoid all logs except for error.
```
We could technically also allow `Log.WARN`, but I'm not sure if that is going to help much.
Fixes #1255
=> fix: turn off camerax info logs

CHANGELOG.md, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt, android/src/main/kotlin/dev/steenbakker/mobile_scanner/objects/MobileScannerStartParameters.kt, darwin/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift, example/lib/scanner_button_widgets.dart, lib/src/enums/camera_facing.dart, lib/src/method_channel/mobile_scanner_method_channel.dart, lib/src/mobile_scanner_controller.dart, lib/src/mobile_scanner_view_attributes.dart, lib/src/objects/mobile_scanner_state.dart, lib/src/web/barcode_reader.dart, lib/src/web/media_track_constraints_delegate.dart, lib/src/web/media_track_extension.dart, lib/src/web/mobile_scanner_web.dart, lib/src/web/zxing/zxing_barcode_reader.dart, test/enums/camera_facing_test.dart
This PR adds the remaining facing modes to the `CameraFacing` enum.
It also passes the actual `CameraFacing` value from the camera to the `MobileScannerState` / surface producer delegate, instead of the requested facing direction. That _should_ help prevent a wrong sign for the orientation correction.
Part of https://github.com/juliansteenbakker/mobile_scanner/issues/867
Work towards fixing https://github.com/juliansteenbakker/mobile_scanner/issues/1319
=> feat: handle more facing directions

darwin/mobile_scanner/Sources/mobile_scanner/MobileScannerPlugin.swift
When the app's orientation is fixed but the device is held in a different direction, the camera view may sometimes appear rotated incorrectly.
- For iOS 13+: Use UIWindowScene.interfaceOrientation for accurate orientation detection.
- Fallback to UIDevice.current.orientation for earlier iOS versions.
=> fix: improve video orientation handling for iOS 13 and above

example/android/gradle.properties
When running the example app, it apparently now fails with a Gradle memory error.
Building the example app did work, oddly enough.
There's an open Flutter tool issue for this, so I took the new JVM args from there :)
=> fix: update gradle JVM args
